name: Synth CDKTF Plan
run-name: ${{ github.actor }} is learning GitHub Actions
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform CDK Synth"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-versions: 20

      - name: Install dependencies
        run: npm install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Test synth
        uses: hashicorp/terraform-cdk-action@v1
        with:
          cdktfVersion: 0.19.2
          terraformVersion: 1.6.5
          mode: synth-only
          stackName: project-yyz-infra
          terraformCloudToken: ${{ secrets.TF_CLOUD_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./deployment
